feat: 🎸 require moderation for maps belonging to anonymous authors and authors with no published maps
publiclab/mapknitter pull request #1786
Opened 2022-07-11 13:28 UTC by PeculiarE

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/mapknitter-reviewers` for help, in a comment below

2022-07-11 14:32 UTC, jywarren requested changes
Hi @PeculiarE I'm sorry if I missed this but i left a comment about the "moderated by default" and its impact on moderator duties. But I think an adjustment to the criteria for publishing as I suggested would be not a huge change to this PR and would work. It would still reduce spam but wouldn't place a burden on moderators to approve each user.

2022-07-11 14:32 UTC, jywarren commented on app/controllers/application_controller.rb
> +  include ActionView::Helpers::DateHelper # required for time_ago_in_words()
Nice and i appreciate the comment!

2022-07-11 14:32 UTC, jywarren commented
Great work, this PR was super readable and a great size for reviewing!

2022-07-11 15:05 UTC, jywarren commented
Well, upon creating a new map, if it's moderated by default, then all new
authors will require a moderator to sign off. If instead we just allow
moderators to go in and remove spam maps, then forbid those users from
making future maps, we don't add a lot of extra work for the moderators,
although some more spam will come through before they catch it.

On Mon, Jul 11, 2022 at 10:56 AM PeculiarE ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In app/models/user.rb
> <https://github.com/publiclab/mapknitter/pull/1786#discussion_r918034799>:
>
> > @@ -71,4 +71,8 @@ def ban
>    def unban
>      update!({ status: Status::NORMAL, status_updated_at: Time.now })
>    end
> +
> +  def needs_moderation?
> +    maps.where(status: Map::Status::NORMAL).count == 0
>
> Could we instead make the threshold be whether the user has a moderated
> map already?
>
> Hmmm...I'm not sure what exactly this means. Could you please clarify? We
> want a map to be moderated only if there's an existing moderated map for
> that user?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/publiclab/mapknitter/pull/1786#discussion_r918034799>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAF6JYFHU4WDUDK4UWY4WDVTQYYVANCNFSM53HQSNLQ>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-07-11 15:13 UTC, PeculiarE commented
So, in essence, no moderation of new maps? All new maps should be published immediately?

2022-07-11 16:18 UTC, jywarren commented
Yes, that's right. Moderation will be upon review only. Well, we can ask
the community reps to confirm this, what do you think?

On Mon, Jul 11, 2022 at 11:13 AM PeculiarE ***@***.***> wrote:

> So, in essence, no moderation of new maps? All new maps should be
> published immediately?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/publiclab/mapknitter/pull/1786#issuecomment-1180537010>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAF6J6DFXJYE2I7AE7BDP3VTQ22DANCNFSM53HQSNLQ>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-07-11 16:32 UTC, jywarren commented
We can mention @ebarry and @publiclab/community-reps as well as reach out
over the chatroom - if to Liz, it can be in the public channel as well.
Thanks!

On Mon, Jul 11, 2022 at 12:31 PM PeculiarE ***@***.***> wrote:

> Alright. Yeah, I think we should.
>
> I'm curious though. The welcome packet lists only ***@***.***
> <https://github.com/ebarry>) as the sole community rep. Are there others?
> Do we simply reach out by sending her a private message on the chat forum,
> or is there a more official process?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/publiclab/mapknitter/pull/1786#issuecomment-1180622204>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAF6J6LOK3C7BFR7KJINFTVTRD5XANCNFSM53HQSNLQ>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-07-11 21:14 UTC, PeculiarE commented
Alright. Thank you!

2022-07-12 16:02 UTC, jywarren commented
@ebarry this applies to anonymous maps as well, right?

@PeculiarE do you think there are parts of this PR we should preserve for other variations of the rules?

I wanted to say I should have caught this as a policy change earlier and I'm sorry for the lost time you spent crafting it @PeculiarE -- I appreciate your efforts. Thank you!

2022-07-12 18:12 UTC, PeculiarE commented
Thank you 😊 @jywarren....I did learn something new in Rails and also realised my misunderstanding/mixup of the first-time-author and new-contributor concepts while working on this. So, there's a silver lining 😄 

> @PeculiarE do you think there are parts of this PR we should preserve for other variations of the rules?

Hmmm....I really can't say which parts are worth preserving at this point. I think it depends on knowing what these variations are/will be. Then we can decide which parts to keep.

I removed the entire commit a few hours ago though 🤦‍♀️ ....but I could easily rewrite the parts we decide that we need

2022-07-21 09:38 UTC, PeculiarE commented
Here's a preview of the new behavior when fetching a single map or a single user if the map has been spammed and/or author has been banned.

Admins/mods can see the status details while other users are redirected.

https://user-images.githubusercontent.com/75625011/180181946-e2b72cfc-313a-4cbb-a775-ee3336472a01.mp4

Is this okay @jywarren, @cesswairimu, @TildaDares?

2022-07-22 21:32 UTC, jywarren commented
Yes, this looks super! Is this ready to merge then? Great work!!

2022-07-22 22:57 UTC, PeculiarE commented
Thank you @jywarren, and yeah, it's okay to merge.

2022-07-26 11:44 UTC, cesswairimu approved these changes
looks great :rocket:

2022-07-26 15:17 UTC, merged

2022-07-26 15:17 UTC, jywarren commented
🎉